### ISSUE TITLE
使用 action 运行错误

### ISSUE THREAD

**Issue by waite0603** [ImYrS/aliyun-auto-signin#44]
使用 github action 运行出现如下报错

```
usage: app.py [-h] [-a] [-d]
app.py: error: unrecognized arguments: action
Error: Process completed with exit code 2.
```

**Comment by ImYrS** [comment]
贴一下你的 action 配置文件

**Comment by waite0603** [comment]
```
name: Aliyun Signin
 
 on:
   schedule:
     # 每天国际时间 16:20 运行一次, 中国时间 00:20
     - cron: '20 16 * * *'
   workflow_dispatch:
 jobs:
   signin:
     name: Aliyun Signin
     runs-on: ubuntu-latest
     steps:
       - uses: ImYrS/aliyun-auto-signin@main
         with:
           REFRESH_TOKENS: ${{ secrets.REFRESH_TOKENS }}
           PUSH_TYPES: 'serverchan'
           SERVERCHAN_SEND_KEY: ${{ secrets.SERVERCHAN_SEND_KEY }}
           TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
           TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
           PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
           SMTP_HOST: ${{ secrets.SMTP_HOST }}
           SMTP_PORT: ${{ secrets.SMTP_PORT }}
           SMTP_TLS: ${{ secrets.SMTP_TLS }}
           SMTP_USER: ${{ secrets.SMTP_USER }}
           SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
           SMTP_SENDER: ${{ secrets.SMTP_SENDER }}
           SMTP_RECEIVER: ${{ secrets.SMTP_RECEIVER }}
```

action Repository secrets 配置了 

REFRESH_TOKENS
SERVERCHAN_SEND_KEY
