### ISSUE TITLE
Github Action  Environment secrets 中的REFRESH_TOKENS不会自动更新

### ISSUE THREAD

**Issue by Carlos920** [ImYrS/aliyun-auto-signin#62]
![image](https://user-images.githubusercontent.com/32257015/233396699-fcb975da-06cf-4155-b602-19fb4b01f7e9.png)

**Comment by ImYrS** [comment]
发一下运行日志

**Comment by Carlos920** [comment]
> 发一下运行日志

![Screenshot_2023-04-21-07-41-40-667_org.telegram.messenger-edit.jpg](https://user-images.githubusercontent.com/32257015/233508774-4e6ec937-e962-4230-a26c-d08073dc4948.jpg)

github action的日志由于替换refush token后我点了重新运行没了，这个773开头的token还是上个月一开始我塞到变量中的，一直没更新过

**Comment by Carlos920** [comment]
> @Carlos920 下面这个是网络问题没签到成功。
> 
> 上面这个 773b 这个之前可以签到吗

20号之前可以，20号开始就不行了

**Comment by ImYrS** [comment]
@Carlos920 733b 的配置文件发一下看看

**Comment by Carlos920** [comment]
> @Carlos920 733b 的配置文件发一下看看


```yml
name: Aliyun Signin

on:
  schedule:
   # 20 17 * * * 每天国际时间 17:20 运行一次, 中国时间 01:20
    - cron: '20 17 * * *'
  workflow_dispatch:
jobs:
  signin:
    name: Aliyun Signin
    runs-on: ubuntu-latest
    environment: aliyun_signin
    steps:
      - uses: ImYrS/aliyun-auto-signin@main
        with:
          REFRESH_TOKENS: ${{ secrets.REFRESH_TOKENS }}
          GP_TOKEN: ${{ secrets.GP_TOKEN}}
          PUSH_TYPES: 'TELEGRAM'
          # DO_NOT_REWARD: 'false'
          # SERVERCHAN_SEND_KEY: ${{ secrets.SERVERCHAN_SEND_KEY }} # [可选] Server酱推送渠道的 SendKey
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }} # [可选] Telegram Bot Token
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }} # [可选] Telegram 接收推送消息的会话 ID
          # PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }} # [可选] PushPlus Token
          # SMTP_HOST: ${{ secrets.SMTP_HOST }} # [可选] SMTP 服务器地址
          # SMTP_PORT: ${{ secrets.SMTP_PORT }} # [可选] SMTP 服务器端口
          # SMTP_TLS: ${{ secrets.SMTP_TLS }} # [可选] SMTP 服务器是否使用 TLS
          # SMTP_USER: ${{ secrets.SMTP_USER }} # [可选] SMTP 服务器用户名
          # SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }} # [可选] SMTP 服务器密码
          # SMTP_SENDER: ${{ secrets.SMTP_SENDER }} # [可选] SMTP 发件人邮箱
          # SMTP_RECEIVER: ${{ secrets.SMTP_RECEIVER }} # [可选] SMTP 收件人邮箱
          # FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }} # [可选] 飞书 Webhook 地址
```
